In [2]:
null_vector=np.zeros(10)

In [3]:
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [12]:
b.shape

(39,)

In [14]:
type(b)

numpy.ndarray

In [16]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'C:\\Users\\Kamran Khawaja\\anaconda3\\lib\\site-packages\\numpy\\version.py'>
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kamran Khawaja/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Kamran Khawaja/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kamran Khawaja/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_librari

In [17]:
np.ndim(b)

1

In [1]:
import numpy as np

In [3]:
b=np.ones(10, dtype =bool)
b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
x= np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
import numpy as np

In [16]:
x= np.zeros([5,5,3])
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ndim(x)

3

In [19]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b= np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [37]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
import numpy as np

In [5]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
null[5-1]=1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
ide=np.identity(3*3)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [6]:
x=np.array([1, 2, 3, 4, 5])
x.astype(float)

array([1., 2., 3., 4., 5.])

In [27]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

In [28]:
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

In [29]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [30]:
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [31]:
arr

array([1, 2, 3, 4, 5])

In [35]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [1]:
import numpy as np

In [4]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [8]:
arr1 =np.arange(9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr1 =np.arange(9)
for item in arr1:
 if item % 2 > 0:
        item = -1
        print(item)
            

-1
-1
-1
-1


In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.put(arr, [5,6,7,8], [12])
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [18]:
arr1 = [1,0,0,1]
arr2 = [1,0,0,1]

In [20]:
z=np.array([arr1 ,arr2])
z

array([[1, 0, 0, 1],
       [1, 0, 0, 1]])

In [29]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.put(arr2d,[4],[12])
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [32]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
np.put(arr3d, [0,1,2], [64,64,64])
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [1]:
import numpy as np


In [7]:
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
x[0, :]

array([0, 1, 2, 3, 4])

In [16]:
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
x[2:2, 2:2]

array([], shape=(0, 0), dtype=int32)

In [22]:
import numpy as np

In [24]:
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
x[2:2,2:2]


array([], shape=(0, 0), dtype=int32)

In [29]:
import numpy as np

In [36]:
a = np.random.rand(10,10)
a

array([[0.61495201, 0.61631967, 0.94935255, 0.20859536, 0.67837474,
        0.71960505, 0.6393406 , 0.07828615, 0.7784462 , 0.40169093],
       [0.91343649, 0.35388325, 0.39340256, 0.45809123, 0.86016858,
        0.3601048 , 0.92914061, 0.38055188, 0.09024137, 0.69428615],
       [0.40480283, 0.34238928, 0.31269609, 0.64805007, 0.78393693,
        0.89029976, 0.89351119, 0.09702368, 0.31311752, 0.29711289],
       [0.09360078, 0.16998313, 0.81495806, 0.28104813, 0.22207039,
        0.91316616, 0.55010629, 0.61658769, 0.34786353, 0.69143107],
       [0.39341739, 0.53182549, 0.04677764, 0.22439549, 0.56959386,
        0.82322092, 0.36326118, 0.4326269 , 0.51025781, 0.87156398],
       [0.25741844, 0.76713191, 0.83725177, 0.54447858, 0.47960483,
        0.66506468, 0.24355324, 0.5499269 , 0.20779526, 0.63565097],
       [0.32112113, 0.02279269, 0.97093336, 0.83166534, 0.43622685,
        0.158541  , 0.29562489, 0.355203  , 0.999277  , 0.18723887],
       [0.28634255, 0.23259418, 0.0846313

In [37]:
np.min(a)

0.02279269432939901

In [38]:
np.max(a)

0.9992770041753914

In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [42]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [4]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [5]:
np.intersect1d(a,b,return_indices=True)

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [8]:
data = np.random.randn(7, 4)
data

array([[-1.37595154,  1.47018291, -0.42960383,  1.88116451],
       [-0.72934671, -0.04193136,  0.71899151, -1.33094439],
       [-0.09250664,  0.71001283,  1.05741047,  0.13149443],
       [-1.94948835, -0.03741524,  0.94979122, -0.02073711],
       [-0.86094029, -0.58154235,  0.84506595, -0.02318289],
       [ 1.17537003, -0.37234841,  0.01592597, -1.30709244],
       [-1.10699981, -1.15935217, -0.40024999, -0.94103411]])

In [11]:
data[names != "Will"]

array([[-1.37595154,  1.47018291, -0.42960383,  1.88116451],
       [-0.72934671, -0.04193136,  0.71899151, -1.33094439],
       [-1.94948835, -0.03741524,  0.94979122, -0.02073711],
       [ 1.17537003, -0.37234841,  0.01592597, -1.30709244],
       [-1.10699981, -1.15935217, -0.40024999, -0.94103411]])

In [16]:
data[names != "Will,Joe"]

array([[-1.37595154,  1.47018291, -0.42960383,  1.88116451],
       [-0.72934671, -0.04193136,  0.71899151, -1.33094439],
       [-0.09250664,  0.71001283,  1.05741047,  0.13149443],
       [-1.94948835, -0.03741524,  0.94979122, -0.02073711],
       [-0.86094029, -0.58154235,  0.84506595, -0.02318289],
       [ 1.17537003, -0.37234841,  0.01592597, -1.30709244],
       [-1.10699981, -1.15935217, -0.40024999, -0.94103411]])

In [11]:
a = np.random.randn(1,15).reshape(5,3)
a

array([[ 0.1965605 , -0.19773717,  0.38278589],
       [-0.06357631,  0.37335814, -2.14115448],
       [ 0.19507997, -0.4325637 ,  1.17567439],
       [-0.83281777,  0.47779392,  1.19287678],
       [-0.42904362, -0.72235596,  1.97833681]])

In [12]:
dec = np.random.randn(1,16).reshape(2,2,4)
dec

array([[[ 1.21124075,  0.11454928,  0.8280844 , -0.83273557],
        [-0.29695234, -0.94914654, -0.89375456,  0.939839  ]],

       [[ 0.40483612,  0.52036285, -0.16426292, -1.45450325],
        [-0.38770816, -0.17523387,  0.05544822,  1.47617594]]])

In [17]:
r=np.arange(10)

In [16]:
np.sqrt(r)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
np.where(r<0.5,0,r)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a=np.random.randint(12)
b=np.random.randint(12)
np.maximum(a,b)

5

In [22]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [25]:
names = set(names)
names

{'Bob', 'Joe', 'Will'}

In [27]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [28]:
 b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [31]:
result = setdiff1d(a,b)
print(result)

NameError: name 'setdiff1d' is not defined