In [1]:
import numpy as np


In [2]:
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
np.shape(x)

(2, 5)

In [7]:
array1=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
arr2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.vstack((array1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
arr=np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])

In [18]:
arr2=np.array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
arr2

array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
np.hstack((arr,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [1]:
import numpy as np

In [2]:
array1=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
b=np.reshape(a,(5,3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
c=np.random.rand(5*5)
c

array([0.36646516, 0.84192858, 0.04822636, 0.08712815, 0.283115  ,
       0.78894979, 0.51778217, 0.44004314, 0.03537464, 0.49833135,
       0.8333254 , 0.95921041, 0.31144695, 0.42229009, 0.87199944,
       0.7771744 , 0.21908955, 0.47748922, 0.58559517, 0.7612938 ,
       0.91875185, 0.37485761, 0.02682163, 0.56893477, 0.98934892])

In [17]:
c*c

array([1.34296714e-01, 7.08843737e-01, 2.32578224e-03, 7.59131460e-03,
       8.01541032e-02, 6.22441764e-01, 2.68098373e-01, 1.93637962e-01,
       1.25136549e-03, 2.48334134e-01, 6.94431218e-01, 9.20084615e-01,
       9.69992057e-02, 1.78328920e-01, 7.60383018e-01, 6.04000045e-01,
       4.80002295e-02, 2.27995960e-01, 3.42921708e-01, 5.79568247e-01,
       8.44104958e-01, 1.40518226e-01, 7.19399624e-04, 3.23686770e-01,
       9.78811282e-01])

In [18]:
b=np.random.rand(5*6)
b

array([0.04028035, 0.08399841, 0.69208106, 0.3412327 , 0.81186541,
       0.38235463, 0.89226746, 0.64251557, 0.67394969, 0.77013461,
       0.6941381 , 0.27369852, 0.88133805, 0.95010177, 0.43315292,
       0.74082779, 0.03732315, 0.92303491, 0.09255681, 0.9018663 ,
       0.49920256, 0.19473231, 0.58720785, 0.1189849 , 0.5949958 ,
       0.40608707, 0.28175061, 0.70599205, 0.16762112, 0.819127  ])

In [19]:
np.mean(b)

0.5211473156269942

In [20]:
np.std(b)

0.294828146048819

In [21]:
np.median(b)

0.5911018264217042

In [22]:
b.T

array([0.04028035, 0.08399841, 0.69208106, 0.3412327 , 0.81186541,
       0.38235463, 0.89226746, 0.64251557, 0.67394969, 0.77013461,
       0.6941381 , 0.27369852, 0.88133805, 0.95010177, 0.43315292,
       0.74082779, 0.03732315, 0.92303491, 0.09255681, 0.9018663 ,
       0.49920256, 0.19473231, 0.58720785, 0.1189849 , 0.5949958 ,
       0.40608707, 0.28175061, 0.70599205, 0.16762112, 0.819127  ])

In [31]:
n = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]])
n

array([[ 55,  25,  15,  41],
       [ 30,  44,   2,  54],
       [ 11,  45,  77,  11],
       [ 11, 212,   4,  20]])

In [34]:
diag = np.diagonal(n) 
diag

array([55, 44, 77, 20])

In [35]:
sum(diag)

196

In [36]:
np.linalg.det(n)

-25166735.999999996

In [37]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.percentile(a,5)

0.45

In [39]:
np.percentile(a,95)

8.549999999999999

In [40]:
np.random.randint(0,3,(3,10))

array([[2, 0, 0, 1, 2, 1, 0, 1, 2, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [2, 1, 1, 0, 1, 2, 0, 1, 0, 0]])